---
# handlers file for entrega02t2_3
  - name: Start ssh
    service:
      name: ssh
      state: started

  - name: Create Admin home
    file:
      path: '{{ homeAdmin }}'
      state: directory
      mode: 0755

  - name: Create Deploy home
    file:
      path: '{{ homeDeploy }}'
      state: directory
      mode: 0755
